test:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  volumes_from: 
    - cache
  links:
    - db
  environment:
    DJANGO_SETTINGS_MODULE: todobackend.settings.test
    MYSQL_HOST: db
    MYSQL_USER: root
    MYSQL_PASSWORD: gno
    TEST_OUTPUT_DIR: /reports

builder:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  volumes: 
    - ../../target:/wheelhouse
  volumes_from: 
    - cache
  entrypoint: "entrypoint.sh"
  command: ["pip",  "wheel",  "--no-index",  "-f /build", "."]


agent:
  image: ansible
  links:
    - db
  environment:
    PROBE_HOST: "db"
    PROBE_PORT: "3306"
  command: ["probe.yml"]
  
cache:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  volumes:
    - d:\DEV\share\wdoc-ansi\cache:/cache
    - /build
  entrypoint: "true"


db:
  image: mysql:5.6
  hostname: db
  expose: 
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: gno

# https://stackoverflow.com/questions/42232051/docker-compose-volumes-from-equivalent-with-version-3
